name: CI/CD - Electiva 2 DevOps

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  ci-notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'   # Última versión LTS

      - name: Compilar y ejecutar Hola Mundo en C#
        run: |
          dotnet new console -o HelloApp --force
          mv Program.cs HelloApp/Program.cs
          cd HelloApp
          dotnet run

      - name: Enviar notificación a ntfy
        run: |
          MSG="🚀 CI/CD - Electiva 2 DevOps%0A\
Build EXITOSO ✅%0A\
Estudiante: Emil Comarazamy #2025-0043\
Curso: Electiva 2 - DevOps%0A\
Profesor: Elvys Cruz%0A\
Repositorio: https://github.com/${GITHUB_REPOSITORY}%0A\
Rama: ${GITHUB_REF_NAME}%0A\
Ver detalles: https://github.com/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}"
          
          curl -s \
            -H "Title: CI/CD - Electiva 2 DevOps" \
            -H "Priority: 5" \
            -H "Tags: rocket,white_check_mark" \
            -d "$MSG" \
            https://ntfy.sh/devops-itla
