name: CI/CD - Electiva 2 DevOps

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  ci-notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Compilar y ejecutar Hola Mundo en C#
        shell: bash
        run: |
          dotnet new console -o HelloApp --force
          # Si ya subiste Program.cs en la raíz, lo movemos dentro del proyecto
          if [ -f Program.cs ]; then
            mv Program.cs HelloApp/Program.cs
          fi
          cd HelloApp
          dotnet build --nologo
          dotnet run

      - name: Enviar notificación a ntfy
        shell: bash
        run: |
          # Construimos el mensaje multilínea SIN escapes raros
          cat <<MSG > message.txt
🚀 CI/CD - Electiva 2 DevOps
Build EXITOSO ✅
Estudiante: Emil Comarazamy #2025-0043
Curso: Electiva 2 - DevOps
Profesor: Elvys Cruz
Repositorio: https://github.com/${GITHUB_REPOSITORY}
Rama: ${GITHUB_REF_NAME}
Ver detalles: https://github.com/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}
MSG

          # Enviamos el contenido del archivo como cuerpo de la petición
          curl -s \
            -H "Title: CI/CD - Electiva 2 DevOps" \
            -H "Priority: 5" \
            -H "Tags: rocket,white_check_mark" \
            --data-binary @message.txt \
            https://ntfy.sh/devops-itla

