name: CI/CD - Electiva 2 DevOps

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  ci-notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Compilar y ejecutar Hola Mundo en C#
        shell: bash
        run: |
          set -e
          dotnet new console -o HelloApp --force
          if [ -f Program.cs ]; then
            mv Program.cs HelloApp/Program.cs
          fi
          cd HelloApp
          dotnet build --nologo
          dotnet run

      - name: Enviar notificación a ntfy
        shell: bash
        env:
          STUDENT: "Emil Comarazamy #2024-0043"     
          REPO: ${{ github.repository }}
          REF_NAME: ${{ github.ref_name }}
          RUN_ID: ${{ github.run_id }}
        run: |
          set -e
          # Construimos el mensaje sin heredocs ni escapes raros
          printf "%s\n" \
            "🚀 CI/CD - Electiva 2 DevOps" \
            "Build EXITOSO ✅" \
            "Estudiante: $STUDENT" \
            "Curso: Electiva 2 - DevOps" \
            "Profesor: Elvys Cruz" \
            "Repositorio: https://github.com/$REPO" \
            "Rama: $REF_NAME" \
            "Ver detalles: https://github.com/$REPO/actions/runs/$RUN_ID" \
            > message.txt

          curl -s \
            -H "Title: CI/CD - Electiva 2 DevOps" \
            -H "Priority: 5" \
            -H "Tags: rocket,white_check_mark" \
            --data-binary @message.txt \
            https://ntfy.sh/devops-itla

